language: node_js
node_js:
  - "lts/*"

# Use faster Docker architecture on Travis.
sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn
  - node get-langs

cache: yarn

script:
  - node stop

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && node upload
